import Head from "next/head";
import { Container, Heading } from "@chakra-ui/react";
import Navbar from "@/components/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Navbar />
      </nav>
      <main>
        <Container maxW="container.xl">
          <Heading>Welcome to Chakra + Next.js</Heading>
          {Array.from(Array(100).keys()).map((n) => (
            <Heading key={n}>Welcome {n}</Heading>
          ))}
        </Container>
      </main>
    </>
  );
}
