import Head from "next/head";
import { Heading } from "@chakra-ui/react";
import ThemeChanger from "@/components/ThemeChanger";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Heading>Welcome to Chakra + Next.js</Heading>
        <ThemeChanger />
      </main>
    </>
  );
}
